CREATE TABLE IF NOT EXISTS hero_sections (
    id INT AUTO_INCREMENT PRIMARY KEY,
    heading VARCHAR(150),
    subheading VARCHAR(150),
    path_video TEXT NULL,
    path_banner TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB;
